// Command gen-chroma-css generates the syntax-highlight stylesheet the frontend
// ships. Ingestion renders code blocks with chroma CSS classes (style-
// independent); this writes the matching colors. Lore is dark-only by design, so
// a single warm theme (gruvbox) is emitted, unscoped.
//
//	cd api && go run ./cmd/gen-chroma-css
//
// Output: web/src/app/chroma.css
package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

const (
	codeStyle = "gruvbox"
	outPath   = "../web/src/app/chroma.css"
)

func main() {
	formatter := html.New(html.WithClasses(true))
	style := styles.Get(codeStyle)
	log.Printf("code style: %s", style.Name)

	var buf bytes.Buffer
	buf.WriteString("/* Generated by cmd/gen-chroma-css. Do not edit by hand. */\n")
	buf.WriteString("/* Code blocks use the surface background from globals.css; only token colors here matter. */\n\n")
	if err := formatter.WriteCSS(&buf, style); err != nil {
		log.Fatalf("write css: %v", err)
	}

	out, err := filepath.Abs(outPath)
	if err != nil {
		log.Fatalf("resolve out path: %v", err)
	}
	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", out, err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", out, buf.Len())
}
