// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentsBySource = `-- name: CountDocumentsBySource :one
SELECT count(*) FROM documents WHERE source_id = $1
`

func (q *Queries) CountDocumentsBySource(ctx context.Context, sourceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDocumentsBySource = `-- name: DeleteDocumentsBySource :exec
DELETE FROM documents WHERE source_id = $1
`

func (q *Queries) DeleteDocumentsBySource(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentsBySource, sourceID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, source_id, slug, path, title, content_html, toc, position, word_count, created_at, updated_at
FROM documents
WHERE source_id = $1 AND slug = $2
`

type GetDocumentParams struct {
	SourceID uuid.UUID `json:"source_id"`
	Slug     string    `json:"slug"`
}

type GetDocumentRow struct {
	ID          uuid.UUID          `json:"id"`
	SourceID    uuid.UUID          `json:"source_id"`
	Slug        string             `json:"slug"`
	Path        string             `json:"path"`
	Title       string             `json:"title"`
	ContentHtml string             `json:"content_html"`
	Toc         json.RawMessage    `json:"toc"`
	Position    int32              `json:"position"`
	WordCount   int32              `json:"word_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.SourceID, arg.Slug)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Slug,
		&i.Path,
		&i.Title,
		&i.ContentHtml,
		&i.Toc,
		&i.Position,
		&i.WordCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsBySource = `-- name: ListDocumentsBySource :many
SELECT id, source_id, slug, path, title, toc, position, word_count, created_at, updated_at
FROM documents
WHERE source_id = $1
ORDER BY position, title
`

type ListDocumentsBySourceRow struct {
	ID        uuid.UUID          `json:"id"`
	SourceID  uuid.UUID          `json:"source_id"`
	Slug      string             `json:"slug"`
	Path      string             `json:"path"`
	Title     string             `json:"title"`
	Toc       json.RawMessage    `json:"toc"`
	Position  int32              `json:"position"`
	WordCount int32              `json:"word_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDocumentsBySource(ctx context.Context, sourceID uuid.UUID) ([]ListDocumentsBySourceRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsBySourceRow{}
	for rows.Next() {
		var i ListDocumentsBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Slug,
			&i.Path,
			&i.Title,
			&i.Toc,
			&i.Position,
			&i.WordCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDocuments = `-- name: PruneDocuments :exec
DELETE FROM documents
WHERE source_id = $1 AND NOT (slug = ANY($2::text[]))
`

type PruneDocumentsParams struct {
	SourceID  uuid.UUID `json:"source_id"`
	KeptSlugs []string  `json:"kept_slugs"`
}

// Removes documents of a source whose slug is no longer present in the latest sync.
func (q *Queries) PruneDocuments(ctx context.Context, arg PruneDocumentsParams) error {
	_, err := q.db.Exec(ctx, pruneDocuments, arg.SourceID, arg.KeptSlugs)
	return err
}

const searchDocuments = `-- name: SearchDocuments :many
WITH search AS (
    SELECT websearch_to_tsquery('english', $3::text) AS tsq
)
SELECT
    d.id,
    d.source_id,
    s.slug AS source_slug,
    s.name AS source_name,
    s.official_url,
    s.license,
    d.slug,
    d.title,
    ts_headline(
        'english',
        d.content_text,
        search.tsq,
        'StartSel=<mark>, StopSel=</mark>, MaxFragments=2, MinWords=6, MaxWords=18'
    )::text AS excerpt,
    ts_rank(d.search_vector, search.tsq)::float8 AS rank
FROM documents d
JOIN sources s ON s.id = d.source_id
CROSS JOIN search
WHERE search.tsq @@ d.search_vector
  AND ($1::text IS NULL OR s.slug = $1::text)
ORDER BY rank DESC, d.title
LIMIT $2::int
`

type SearchDocumentsParams struct {
	SourceSlug  *string `json:"source_slug"`
	LimitCount  int32   `json:"limit_count"`
	SearchQuery string  `json:"search_query"`
}

type SearchDocumentsRow struct {
	ID          uuid.UUID `json:"id"`
	SourceID    uuid.UUID `json:"source_id"`
	SourceSlug  string    `json:"source_slug"`
	SourceName  string    `json:"source_name"`
	OfficialUrl string    `json:"official_url"`
	License     *string   `json:"license"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Excerpt     string    `json:"excerpt"`
	Rank        float64   `json:"rank"`
}

func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments, arg.SourceSlug, arg.LimitCount, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.SourceSlug,
			&i.SourceName,
			&i.OfficialUrl,
			&i.License,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (
    id, source_id, slug, path, title, content_html, content_text, toc, position, word_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (source_id, slug) DO UPDATE SET
    path         = EXCLUDED.path,
    title        = EXCLUDED.title,
    content_html = EXCLUDED.content_html,
    content_text = EXCLUDED.content_text,
    toc          = EXCLUDED.toc,
    position     = EXCLUDED.position,
    word_count   = EXCLUDED.word_count,
    updated_at   = now()
RETURNING id
`

type UpsertDocumentParams struct {
	ID          uuid.UUID       `json:"id"`
	SourceID    uuid.UUID       `json:"source_id"`
	Slug        string          `json:"slug"`
	Path        string          `json:"path"`
	Title       string          `json:"title"`
	ContentHtml string          `json:"content_html"`
	ContentText string          `json:"content_text"`
	Toc         json.RawMessage `json:"toc"`
	Position    int32           `json:"position"`
	WordCount   int32           `json:"word_count"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.ID,
		arg.SourceID,
		arg.Slug,
		arg.Path,
		arg.Title,
		arg.ContentHtml,
		arg.ContentText,
		arg.Toc,
		arg.Position,
		arg.WordCount,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
