// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SourceIngestType string

const (
	SourceIngestTypeGithubMarkdown SourceIngestType = "github_markdown"
)

func (e *SourceIngestType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceIngestType(s)
	case string:
		*e = SourceIngestType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceIngestType: %T", src)
	}
	return nil
}

type NullSourceIngestType struct {
	SourceIngestType SourceIngestType `json:"source_ingest_type"`
	Valid            bool             `json:"valid"` // Valid is true if SourceIngestType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceIngestType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceIngestType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceIngestType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceIngestType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceIngestType), nil
}

type SourceKind string

const (
	SourceKindLanguage  SourceKind = "language"
	SourceKindFramework SourceKind = "framework"
	SourceKindLibrary   SourceKind = "library"
	SourceKindTool      SourceKind = "tool"
)

func (e *SourceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceKind(s)
	case string:
		*e = SourceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceKind: %T", src)
	}
	return nil
}

type NullSourceKind struct {
	SourceKind SourceKind `json:"source_kind"`
	Valid      bool       `json:"valid"` // Valid is true if SourceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceKind) Scan(value interface{}) error {
	if value == nil {
		ns.SourceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceKind), nil
}

type SourceStatus string

const (
	SourceStatusActive   SourceStatus = "active"
	SourceStatusSyncing  SourceStatus = "syncing"
	SourceStatusError    SourceStatus = "error"
	SourceStatusDisabled SourceStatus = "disabled"
)

func (e *SourceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceStatus(s)
	case string:
		*e = SourceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceStatus: %T", src)
	}
	return nil
}

type NullSourceStatus struct {
	SourceStatus SourceStatus `json:"source_status"`
	Valid        bool         `json:"valid"` // Valid is true if SourceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SourceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceStatus), nil
}

type SyncStatus string

const (
	SyncStatusRunning SyncStatus = "running"
	SyncStatusSuccess SyncStatus = "success"
	SyncStatusError   SyncStatus = "error"
)

func (e *SyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncStatus(s)
	case string:
		*e = SyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncStatus: %T", src)
	}
	return nil
}

type NullSyncStatus struct {
	SyncStatus SyncStatus `json:"sync_status"`
	Valid      bool       `json:"valid"` // Valid is true if SyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncStatus), nil
}

type Document struct {
	ID           uuid.UUID          `json:"id"`
	SourceID     uuid.UUID          `json:"source_id"`
	Slug         string             `json:"slug"`
	Path         string             `json:"path"`
	Title        string             `json:"title"`
	ContentHtml  string             `json:"content_html"`
	ContentText  string             `json:"content_text"`
	Toc          json.RawMessage    `json:"toc"`
	Position     int32              `json:"position"`
	WordCount    int32              `json:"word_count"`
	SearchVector interface{}        `json:"search_vector"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Source struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	Kind         SourceKind         `json:"kind"`
	Category     string             `json:"category"`
	Description  string             `json:"description"`
	LogoUrl      *string            `json:"logo_url"`
	OfficialUrl  string             `json:"official_url"`
	License      *string            `json:"license"`
	Version      *string            `json:"version"`
	IngestType   SourceIngestType   `json:"ingest_type"`
	IngestConfig json.RawMessage    `json:"ingest_config"`
	Nav          json.RawMessage    `json:"nav"`
	Status       SourceStatus       `json:"status"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SyncRun struct {
	ID                 uuid.UUID          `json:"id"`
	SourceID           uuid.UUID          `json:"source_id"`
	Status             SyncStatus         `json:"status"`
	DocumentsProcessed int32              `json:"documents_processed"`
	ErrorMessage       *string            `json:"error_message"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
}
