// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountDocumentsBySource(ctx context.Context, sourceID uuid.UUID) (int64, error)
	CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error)
	DeleteDocumentsBySource(ctx context.Context, sourceID uuid.UUID) error
	FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error
	GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error)
	GetLatestSyncRun(ctx context.Context, sourceID uuid.UUID) (SyncRun, error)
	GetSourceByID(ctx context.Context, id uuid.UUID) (Source, error)
	GetSourceBySlug(ctx context.Context, slug string) (Source, error)
	ListDocumentsBySource(ctx context.Context, sourceID uuid.UUID) ([]ListDocumentsBySourceRow, error)
	ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error)
	ListSyncRunsBySource(ctx context.Context, arg ListSyncRunsBySourceParams) ([]SyncRun, error)
	MarkSourceSynced(ctx context.Context, arg MarkSourceSyncedParams) error
	// Removes documents of a source whose slug is no longer present in the latest sync.
	PruneDocuments(ctx context.Context, arg PruneDocumentsParams) error
	SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error)
	SetSourceNav(ctx context.Context, arg SetSourceNavParams) error
	SetSourceStatus(ctx context.Context, arg SetSourceStatusParams) error
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (uuid.UUID, error)
	UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error)
}

var _ Querier = (*Queries)(nil)
