// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, slug, name, kind, category, description, logo_url, official_url, license, version, ingest_type, ingest_config, nav, status, last_synced_at, created_at, updated_at FROM sources WHERE id = $1
`

func (q *Queries) GetSourceByID(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Category,
		&i.Description,
		&i.LogoUrl,
		&i.OfficialUrl,
		&i.License,
		&i.Version,
		&i.IngestType,
		&i.IngestConfig,
		&i.Nav,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceBySlug = `-- name: GetSourceBySlug :one
SELECT id, slug, name, kind, category, description, logo_url, official_url, license, version, ingest_type, ingest_config, nav, status, last_synced_at, created_at, updated_at FROM sources WHERE slug = $1
`

func (q *Queries) GetSourceBySlug(ctx context.Context, slug string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceBySlug, slug)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Category,
		&i.Description,
		&i.LogoUrl,
		&i.OfficialUrl,
		&i.License,
		&i.Version,
		&i.IngestType,
		&i.IngestConfig,
		&i.Nav,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, slug, name, kind, category, description, logo_url, official_url, license, version, ingest_type, ingest_config, nav, status, last_synced_at, created_at, updated_at FROM sources
WHERE ($1::source_kind IS NULL OR kind = $1::source_kind)
  AND ($2::text IS NULL OR category = $2::text)
ORDER BY category, name
`

type ListSourcesParams struct {
	Kind     *SourceKind `json:"kind"`
	Category *string     `json:"category"`
}

func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, arg.Kind, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Category,
			&i.Description,
			&i.LogoUrl,
			&i.OfficialUrl,
			&i.License,
			&i.Version,
			&i.IngestType,
			&i.IngestConfig,
			&i.Nav,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSourceSynced = `-- name: MarkSourceSynced :exec
UPDATE sources
SET status = $2, last_synced_at = now(), updated_at = now()
WHERE id = $1
`

type MarkSourceSyncedParams struct {
	ID     uuid.UUID    `json:"id"`
	Status SourceStatus `json:"status"`
}

func (q *Queries) MarkSourceSynced(ctx context.Context, arg MarkSourceSyncedParams) error {
	_, err := q.db.Exec(ctx, markSourceSynced, arg.ID, arg.Status)
	return err
}

const setSourceNav = `-- name: SetSourceNav :exec
UPDATE sources SET nav = $2, updated_at = now() WHERE id = $1
`

type SetSourceNavParams struct {
	ID  uuid.UUID       `json:"id"`
	Nav json.RawMessage `json:"nav"`
}

func (q *Queries) SetSourceNav(ctx context.Context, arg SetSourceNavParams) error {
	_, err := q.db.Exec(ctx, setSourceNav, arg.ID, arg.Nav)
	return err
}

const setSourceStatus = `-- name: SetSourceStatus :exec
UPDATE sources SET status = $2, updated_at = now() WHERE id = $1
`

type SetSourceStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status SourceStatus `json:"status"`
}

func (q *Queries) SetSourceStatus(ctx context.Context, arg SetSourceStatusParams) error {
	_, err := q.db.Exec(ctx, setSourceStatus, arg.ID, arg.Status)
	return err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (
    id, slug, name, kind, category, description,
    logo_url, official_url, license, version, ingest_type, ingest_config
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (slug) DO UPDATE SET
    name          = EXCLUDED.name,
    kind          = EXCLUDED.kind,
    category      = EXCLUDED.category,
    description   = EXCLUDED.description,
    logo_url      = EXCLUDED.logo_url,
    official_url  = EXCLUDED.official_url,
    license       = EXCLUDED.license,
    version       = EXCLUDED.version,
    ingest_type   = EXCLUDED.ingest_type,
    ingest_config = EXCLUDED.ingest_config,
    updated_at    = now()
RETURNING id, slug, name, kind, category, description, logo_url, official_url, license, version, ingest_type, ingest_config, nav, status, last_synced_at, created_at, updated_at
`

type UpsertSourceParams struct {
	ID           uuid.UUID        `json:"id"`
	Slug         string           `json:"slug"`
	Name         string           `json:"name"`
	Kind         SourceKind       `json:"kind"`
	Category     string           `json:"category"`
	Description  string           `json:"description"`
	LogoUrl      *string          `json:"logo_url"`
	OfficialUrl  string           `json:"official_url"`
	License      *string          `json:"license"`
	Version      *string          `json:"version"`
	IngestType   SourceIngestType `json:"ingest_type"`
	IngestConfig json.RawMessage  `json:"ingest_config"`
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, upsertSource,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.Category,
		arg.Description,
		arg.LogoUrl,
		arg.OfficialUrl,
		arg.License,
		arg.Version,
		arg.IngestType,
		arg.IngestConfig,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Category,
		&i.Description,
		&i.LogoUrl,
		&i.OfficialUrl,
		&i.License,
		&i.Version,
		&i.IngestType,
		&i.IngestConfig,
		&i.Nav,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
