// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (id, source_id, status)
VALUES ($1, $2, 'running')
RETURNING id, source_id, status, documents_processed, error_message, started_at, finished_at
`

type CreateSyncRunParams struct {
	ID       uuid.UUID `json:"id"`
	SourceID uuid.UUID `json:"source_id"`
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, createSyncRun, arg.ID, arg.SourceID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Status,
		&i.DocumentsProcessed,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE sync_runs
SET status = $2, documents_processed = $3, error_message = $4, finished_at = now()
WHERE id = $1
`

type FinishSyncRunParams struct {
	ID                 uuid.UUID  `json:"id"`
	Status             SyncStatus `json:"status"`
	DocumentsProcessed int32      `json:"documents_processed"`
	ErrorMessage       *string    `json:"error_message"`
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncRun,
		arg.ID,
		arg.Status,
		arg.DocumentsProcessed,
		arg.ErrorMessage,
	)
	return err
}

const getLatestSyncRun = `-- name: GetLatestSyncRun :one
SELECT id, source_id, status, documents_processed, error_message, started_at, finished_at FROM sync_runs
WHERE source_id = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncRun(ctx context.Context, sourceID uuid.UUID) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getLatestSyncRun, sourceID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Status,
		&i.DocumentsProcessed,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listSyncRunsBySource = `-- name: ListSyncRunsBySource :many
SELECT id, source_id, status, documents_processed, error_message, started_at, finished_at FROM sync_runs
WHERE source_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListSyncRunsBySourceParams struct {
	SourceID uuid.UUID `json:"source_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListSyncRunsBySource(ctx context.Context, arg ListSyncRunsBySourceParams) ([]SyncRun, error) {
	rows, err := q.db.Query(ctx, listSyncRunsBySource, arg.SourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncRun{}
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Status,
			&i.DocumentsProcessed,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
